### ISSUE TITLE
Add exclusive write open to not overwrite current output file

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/fms_yaml_tools#18]
It was suggested during the workflow meeting to have the yaml tool not overwrite an existing file, by default.  This can be done with the `x` option to `open()`.

**Comment by uramirez8707** [comment]
All tools now have a `--force-write` option
https://github.com/NOAA-GFDL/fms_yaml_tools/blob/f30da1113d924859dbe3b776e2b5ac17808d4aac/fms_yaml_tools/data_table/data_table_to_yaml.py#L35-L36

https://github.com/NOAA-GFDL/fms_yaml_tools/blob/f30da1113d924859dbe3b776e2b5ac17808d4aac/fms_yaml_tools/data_table/data_table_to_yaml.py#L60-L62
