### ISSUE TITLE
Add pip-install scripts

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fms_yaml_tools#9]
@underwoo suggested that the 3 converters in this repository be pip-installable, and be integrated into FRE with their python dependencies.

The idea would be to install these python tools as a standard python package:

https://packaging.python.org/en/latest/tutorials/installing-packages/

**Comment by underwoo** [comment]
What I showed during the [tutorial](https://cobweb.gfdl.noaa.gov/~Seth.Underwood/pip) can be found on my [fork](https://github.com/underwoo/fms_yaml_tools/tree/pip.primer).
